### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by key-hh** [key-hh/chat-example#1]
- [x] one to one chat (room based)
- [ ] room manager
- [ ] STOMP protocol
- [ ] redis -> nats or kafka (message delivery guarantee)
- [ ] load unread message history
